[package]
name = "chunk_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
futures = "0.3.31"
num_cpus = "1.17.0"
priority-queue = "2.5.0"
rand = "0.9.2"
rayon = "1.11.0"
tokio = { version = "1.47.1", features = ["full"] }
